name: Java with Nexus Repository

on:
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Maven Deploy
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/edp20 -Dtoken=${{ secrets.GITHUB_TOKEN }}
#    - name: Nexus Repo Publish
#      uses: sonatype-nexus-community/nexus-repo-github-action@master
#      with:
#        serverUrl: http://52.228.32.176:8081
#        username: admin
#        password: ${{ secrets.nexus_password }}
#        format: maven2
#        repository: its-maven-releases
#        coordinates: groupId=hello artifactId=gs-spring-boot version=1.0.0
#        assets: extension=war
#        filename: ./target/gs-spring-boot-1.0.0.war